### ISSUE TITLE
The wallet can be selected for signing during https://allocator.tech/ signing process.

### ISSUE THREAD

**Issue by luhong123** [fidlabs/allocator-tooling#10]
During the signing process, it was found that the tool selects the first wallet by default, and the first wallet is not in the list of multi-signing wallets, so it causes the signature to fail

Please add this feature as soon as possible as some wallets are private property and cannot be used

**Comment by kevzak** [comment]
I am also having this issue when trying to sign. How can I change the f1 address from my ledger to match the designated allocator f1 address?

<img width="928" alt="image" src="https://github.com/fidlabs/allocator-tooling/assets/102751751/99fe264f-e5e8-48c7-a362-551597203b67">

**Comment by clriesco** [comment]
Closed as completed
