### ISSUE TITLE
The new allocator application form is experiencing a bug where we are unable to make any selections.

### ISSUE THREAD

**Issue by fengfeihuimin** [fidlabs/allocator-tooling#101]
Dear Official Team,

When we began the application process for a new automated allocator, we encountered a bug in the application form. Specifically, under the section "Tooling, Bookkeeping, and Allocation Schedule: Allocation Tranche Schedule Type," we are unable to select any options. We have also tried using different browsers, but the issue persists. Could you please advise on how we can resolve this problem?

<img width="1093" alt="image" src="https://github.com/user-attachments/assets/d0b4d542-b881-47a5-aed4-77ef7e0f73a9" />

<img width="1077" alt="image" src="https://github.com/user-attachments/assets/933d452e-7754-4233-8b95-dc7ad89b18c5" />

You can try opening the application form yourself; you will find that no selection can be made.
https://airtable.com/app64ajISFdqLB7XK/pagJzPpLypcEH5Cd3/form

Thank you for your assistance.

Best regards,
StellarStake Allocator

**Comment by fengfeihuimin** [comment]
@martapiekarska

**Comment by martapiekarska** [comment]
Thi is fixed now

**Comment by fengfeihuimin** [comment]
@martapiekarska Thank you very much！
