### ISSUE TITLE
No allocators show if I don't have any allocator

### ISSUE THREAD

**Issue by martapiekarska** [fidlabs/allocator-tooling#11]
When going to allocator.tech and logging in with my gihub account, if there is no allocator connected to that gihub handle, 
EXPECTED BEHAVIOUR: I should see all the allocators
ACTUAL BEHAVIOUR: no allocators show up. There is no drop down to select "view all"

<img width="1224" alt="image" src="https://github.com/fidlabs/allocator-tooling/assets/4159990/689bcbc4-b859-4ed5-84f0-ddeb0b225b40">

**Comment by kevzak** [comment]
This is because KWray is not an allocator. Perhaps he needs an admin login? Or if he looks at the main screen, he can see the list.
