### ISSUE TITLE
More lenient parsing of numeric values

### ISSUE THREAD

**Issue by kevzak** [fidlabs/allocator-tooling#12]
On [this application](https://github.com/fidlabs/Enterprise-Data-Pathway/issues/3), the original values that should be numerical were input incorrectly. (FYI it is confusing as a user, I agree)

The values have been updated
<img width="423" alt="image" src="https://github.com/fidlabs/allocator-tooling/assets/102751751/fdbf1efb-66a5-4c4c-b4e6-de3c677ccf18">

but the view on allocator.tech is still showing 0. How to sync with edited application? Is it possible?

<img width="945" alt="image" src="https://github.com/fidlabs/allocator-tooling/assets/102751751/0252694b-49ea-47a8-bc64-88be4e2211cb">

**Comment by willscott** [comment]
fwiw - here's what original was that,as expected, didn't parse 
<img width="488" alt="image" src="https://github.com/fidlabs/allocator-tooling/assets/428199/cfc15763-63bb-4aea-8d8a-506bab5cf2b3">

**Comment by kevzak** [comment]
exactly, users enter number and unit in the same line. I've seen it mulitple times now. 

Can it be edited and reflected properly?
