### ISSUE TITLE
Bot triggers second allocation review hours after the first - should be after 75% usage

### ISSUE THREAD

**Issue by kevzak** [fidlabs/allocator-tooling#18]
Here are two examples where the initial allocation is approved, and the bot creates an "Application Granted" and "Application in Refill" comment together and triggers the next allocation request.

There is no way the client used 75% of DataCap to trigger next request.

Two examples:

https://github.com/MikeH1999/RFfil/issues/3#issuecomment-2017166847

https://github.com/fidlabs/Enterprise-Data-Pathway/issues/3#issuecomment-2015403561

**Comment by kevzak** [comment]
Also - the second request was for 512TiB. Where are these allocation numbers coming from? 

https://github.com/MikeH1999/RFfil/issues/3#issuecomment-2017167018

**Comment by kevzak** [comment]
Seems like these clients are using addresses from older LDN applications. The usage of the same address across applications likely causes issues in allocation calculations and reminders.

**Comment by Lind111** [comment]
https://github.com/Lind111/EF/issues/9#issuecomment-2031230178

I also encountered a similar issue here, which triggered again one hour after manually signing ` ready to sign`

**Comment by kacperzuk-neti** [comment]
75% bot was reworked completely since this issue was reported and it seems this issue was fixed.
