### ISSUE TITLE
If logged in user can not perform the next expected action on an application, make it clear why

### ISSUE THREAD

**Issue by willscott** [fidlabs/allocator-tooling#19]
currently, an application may show in the list as 'pending review'. when the logged in user views the app, they see no call to action / next step to take. Instead of the button, there should be text shown in this case saying that the user doesn't have permission to perform the action. ("you are authenticated as _user_, only _registry user_ is able to perform the review step"

**Comment by kevzak** [comment]
@willscott I would add a feature related here. There should be a button to deny DataCap based on review and close a registry item. Not only have the option to approve.

**Comment by kevzak** [comment]
<img width="899" alt="image" src="https://github.com/fidlabs/allocator-tooling/assets/102751751/1bf6cb56-709e-417f-a0ea-7d58c4dc0e62">

**Comment by AlexMCon** [comment]
This should be closed as it's done, I think
