### ISSUE TITLE
handle ".git" suffix from repo if present

### ISSUE THREAD

**Issue by willscott** [fidlabs/allocator-tooling#20]
currently, allocator-bookkeeping is used for repo name, and can't handle the ".git" suffix form of the repo url. It should also handle this form.

**Comment by NDLABS-Leo** [comment]
https://github.com/filecoin-project/notary-governance/issues/1026
https://github.com/filecoin-project/notary-governance/issues/1025

**Comment by clriesco** [comment]
Closed as completed

**Comment by CockroachBoss** [comment]
https://github.com/filecoin-project/notary-governance/issues/1029
