### ISSUE TITLE
Handle capitalization of github usernames

### ISSUE THREAD

**Issue by willscott** [fidlabs/allocator-tooling#21]
if allocator-registry has a variant of usernames with capitalization, it should be normalized, as capitalization does not matter to github.

**Comment by Fatman13** [comment]
Any progress on this issue?

**Comment by Fatman13** [comment]
Trying to fix it through registry PR per suggestion by @galen during governance call.

**Comment by willscott** [comment]
@AlexMCon  - we don't yet have a deployed version that normalizes capitalization from what I can tell

**Comment by AlexMCon** [comment]
This can be closed. Should be fixed!
