### ISSUE TITLE
Always sign failed（hope change the sign address ）

### ISSUE THREAD

**Issue by Chuangshi1** [fidlabs/allocator-tooling#22]
We are Genesis, and i need your help. This is our application https://github.com/filecoin-project/notary-governance/issues/1019  
There are two addresses in our ledger :
f1ldkhvk55psquvhc727udmdl2tgm55exndh2meqa and f1mdk7s2vntzm6hu35yuo6vjubtrpfnb2awhgvrri                                    
 we didn't create the multsign.
I offer f1ldkhvk55psquvhc727udmdl2tgm55exndh2meqa to you for V5 allocator in the #1019. But when i test allocator sign, it only show picture like this . 
![1711594864038](https://github.com/fidlabs/allocator-tooling/assets/112937825/b0567710-58e2-4f67-bb5b-bf5225ccead9)
Maybe something wrong with my ledger. It can't show f1ldkhvk55psquvhc727udmdl2tgm55exndh2meqa address when i sign. 
Maybe you can help us change the sign address 
Or maybe something else. 
Hope you can help us the last step test.
Thank you so much, sincerely
@willscott @Kwray @Galen

**Comment by willscott** [comment]
It looks like this may be related to #10 
- are we potentially using a different derivation path than ledger in identifying wallets?

**Comment by Chuangshi1** [comment]
> It looks like this may be related to #10
> 
> * are we potentially using a different derivation path than ledger in identifying wallets?

When we use other ledger with the 3rd address sign, it will show the 3rd address.
