### ISSUE TITLE
Failure of robot to get template data

### ISSUE THREAD

**Issue by MikeH1999** [fidlabs/allocator-tooling#23]
Failure Condition Reference
https://github.com/MikeH1999/RFfil/issues/8
![image](https://github.com/fidlabs/allocator-tooling/assets/149572051/91a6f5e1-6326-4789-a9ac-fec98b2f35ce)
![image](https://github.com/fidlabs/allocator-tooling/assets/149572051/a5ff0f26-dbd5-4436-b9c6-afd6c65d877f)
![image](https://github.com/fidlabs/allocator-tooling/assets/149572051/ec269a1c-d542-4858-b40e-fe9687cd8f68)

----------------------------------------------------------------------------------------------------------------------------

Tested to be filled out completely to get the correct values
https://github.com/MikeH1999/RFfil/issues/10
![image](https://github.com/fidlabs/allocator-tooling/assets/149572051/567ce4f9-6f2a-42ea-810f-d359387bd501)
![image](https://github.com/fidlabs/allocator-tooling/assets/149572051/22e64d1c-e1aa-4a42-b16b-1d360b3b0887)
![image](https://github.com/fidlabs/allocator-tooling/assets/149572051/f7be03a0-022a-486c-a135-7a37e7e8af7f)

**Comment by clriesco** [comment]
Hello! We have already fixed this and modified the validation schema. It should work right now. Thx for the feedback!
