### ISSUE TITLE
additional allocator.tech statuses needed

### ISSUE THREAD

**Issue by kevzak** [fidlabs/allocator-tooling#25]
Currently the status field shows several different statuses on allocator.tech, including: 
- 'Pending Governance Review'
- 'Ready to sign - Initial'
- 'Ready to sign - Refill'
- 'Granted'

Completing the review and signing should not be the only options. 

Completing governance review requests should also have the options to:
- decline the request. 'Declined'
- Or to send a message to ask a client to update their application information (ex: they did not provide enough detail about dataset) 'Additional information from client requested'
- Or if an issue is closed, perhaps a status of 'Closed'? Or move the request off of the open list of issues showing?

**Comment by kevzak** [comment]
also the term 'governance' should be switched to 'allocator' perhaps? It's confusing when i see this.

**Comment by willscott** [comment]
> also the term 'governance' should be switched to 'allocator' perhaps?

this is done. e.g. 
https://github.com/filplus-bookkeeping/Bitengine-Reeta-Filplus/issues/1#issuecomment-2034000395

**Comment by clriesco** [comment]
For closed issues, we will add a "closed" tag for now. If you want the issue to be closed and deleted, just let us know

**Comment by clriesco** [comment]
Closed as completed
