### ISSUE TITLE
editing allocation values on subsequent allocation requests

### ISSUE THREAD

**Issue by kevzak** [fidlabs/allocator-tooling#26]
Currently you cannot edit allocation amounts on subsequent requests within Allocator.tech. You can only sign the previous requested amount. 

![image](https://github.com/fidlabs/allocator-tooling/assets/102751751/bca9377f-7d28-4545-882a-c2cdf1411741)

It would be good to edit any subsequent allocation as well.

**Comment by willscott** [comment]
you can edit the subsequent PR following the faq steps we've already released.

It does sounds like there's a 'deny' button here / something that prompts for doing that review at re-request time that isn't exposed to users currently

**Comment by AlexMCon** [comment]
This should be closed as it's done, I think
