### ISSUE TITLE
Item remains in ux frontent after corresponding issue and PR are closed in github

### ISSUE THREAD

**Issue by willscott** [fidlabs/allocator-tooling#32]
<img width="1478" alt="image" src="https://github.com/fidlabs/allocator-tooling/assets/428199/c46ee6b3-59dd-448c-aa09-893ef3c106b9">

we see this in a pending state, 19 hours after the corresponding issue is closed, and after the cache refresh action is triggered. (which commented and changed status on the closed issue)

**Comment by willscott** [comment]
this is downstream that there's no way to say 'no' to a refill / request in the frontend - the request is that there should be a way to say 'close' / 'deny refill' in the frontend

**Comment by willscott** [comment]
P2: cancel pending transactions in the blockchain
P2: closing of an issue could trigger to status closed

**Comment by clriesco** [comment]
Related to https://github.com/fidlabs/allocator-tooling/issues/25

**Comment by AlexMCon** [comment]
This should be closed as it's done, I think
