### ISSUE TITLE
Allocator.tech always shows 'slingshot' as the data type. 

### ISSUE THREAD

**Issue by kevzak** [fidlabs/allocator-tooling#33]
When I review an actual application the data type is Private. But in Allocator.tech view, its slingshot.

![image](https://github.com/fidlabs/allocator-tooling/assets/102751751/36b883cd-32f2-4e43-bcda-fc9ca3936ac8)

![image](https://github.com/fidlabs/allocator-tooling/assets/102751751/e206ba8e-30d6-4d75-9e6a-a24a50298e07)

All applications show Slingshot. Also, Slingshot should not even be an option, it should be removed from the drop down list in the master template.

**Comment by clriesco** [comment]
We'll hide this value in allocator.tech

**Comment by clriesco** [comment]
Closed as completed
