### ISSUE TITLE
Need button to trigger SA bot in allocator.tech

### ISSUE THREAD

**Issue by willscott** [fidlabs/allocator-tooling#36]
There are cases, e.g.

https://datacapstats.io/clients/f03045819
https://allocator.tech/application/NDLABS-Leo/Allocator-Pathway-ND-CLOUD/f1pdtlhokxk4w2xk3hny7u4styeuisjintboztcvy
where sa bot should have triggered but hasn't - there should be some button to trigger the bot if it hasn’t triggered on it’s own

**Comment by clriesco** [comment]
if a new SA hasn't been triggered it will be most likely due to an error with the application itself. The best workaround for this should be posting a message in the issue (or send a warning message to the dev team) about this.

**Comment by kacperzuk-neti** [comment]
Done.
