### ISSUE TITLE
Unable to sign - Allocator.tech

### ISSUE THREAD

**Issue by Kevin-FF-USA** [fidlabs/allocator-tooling#48]
Filed on behalf of SPACET9 

Issue:  Unable to sign in Allocator.tech

Application: https://allocator.tech/application/StorSwift-team/fil-allocator-bookkeeping/f1fmcgclzh7m7pmi3i7qgz3ujpsv5ml5uhhpjeogy

![image](https://github.com/fidlabs/allocator-tooling/assets/94004586/df93d2fc-c2cb-4710-98b2-30b464ef099a)

**Comment by galen-mcandrew** [comment]
@willscott Can we check on this and provide an update for spacet9? Thanks

**Comment by willscott** [comment]
i believe this should be fixed.

if not, spacet9 - can you open the developer console when you get the error and take a screenshot or paste errors that appear there?
