### ISSUE TITLE
Unable to sign,No refill label- Allocator.tech

### ISSUE THREAD

**Issue by AlanGreaterheat** [fidlabs/allocator-tooling#49]
![image](https://github.com/fidlabs/allocator-tooling/assets/110453718/b58ca7d7-3a10-48fb-a049-0dd91644ae37)

![image](https://github.com/fidlabs/allocator-tooling/assets/110453718/e11bc8bc-578d-4f9f-b15a-5b0d2a832192)

Hi,doesn't look like it's been triggered, no refill logo appears, even though there's only 12 TiB left in the first round quota.

https://github.com/pandacrypto/DSPA-Allocator/issues/11

**Comment by AlanGreaterheat** [comment]
Hi,any feedback？

**Comment by willscott** [comment]
We're actively working on adding a way to manually trigger a refill in these cases - tracking the work under https://github.com/fidlabs/allocator-tooling/issues/36

**Comment by willscott** [comment]
this should be resolved / there's now a manual button to trigger in cases where the bot is confused
