### ISSUE TITLE
The remaining allocation amount of the total allocation amount is incorrect

### ISSUE THREAD

**Issue by MikeH1999** [fidlabs/allocator-tooling#50]
![image](https://github.com/fidlabs/allocator-tooling/assets/149572051/0614d6dc-be93-4f02-bb66-fc5fd771a16f)
As shown above.
I have only allocated 3 rounds of datacap, which are 20 60 80, and when I allocate the fourth round, according to my allocation rules the fourth round should be allocated 120Tib yet it says 'Amount is bigger than remaning'
![image](https://github.com/fidlabs/allocator-tooling/assets/149572051/c33c870b-c7d2-4aea-af6d-3d1f5d10b9b3)
Checked and found that the 200Tib unallocated amount automatically triggered by the bot was also added to the Total Allocation Amount, so that caused this to happen

LDN:https://github.com/MikeH1999/RFfil/issues/23

**Comment by NDLABS-Leo** [comment]
https://github.com/NDLABS-Leo/Allocator-Pathway-Enterprise-data/issues/3

Same thing happens.

**Comment by kevzak** [comment]
@NDLABS-Leo @MikeH1999 - this issue is being addressed by dev team shortly. The auto subsequent amount bot will be disabled and allocators will need to go to allocator.tech and enter the exact amount they wish to allocate, same as the first allocation.

**Comment by kacperzuk-neti** [comment]
@NDLABS-Leo @MikeH1999 we've deployed a change that should resolve this issue. Please try again and let us know if it works now.

**Comment by MikeH1999** [comment]
Great, we've successfully changed the trigger value.
![image](https://github.com/fidlabs/allocator-tooling/assets/149572051/2bc1a898-1f8b-4504-88e4-3ade57a28f36)

**Comment by NDLABS-Leo** [comment]
@kacperzuk-neti @kevzak 
I've managed to complete the signatures, thanks for the work guys!
