### ISSUE TITLE
Wrong Link in details of application

### ISSUE THREAD

**Issue by martapiekarska** [fidlabs/allocator-tooling#51]
When I open detailed view of a client application on allocator.tech and then click the issue number to view the application details, it  takes me to https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/<issue number> 

Expected behaviour: it should take me to  https://github.com/<allocator's github handle>/<allocator repository/<issue number>

When using the link on the general view page, it directs me to the correct github link 
<img width="1040" alt="image" src="https://github.com/fidlabs/allocator-tooling/assets/4159990/2413f334-c89b-4f59-831e-32d5930e4780">

**Comment by kacperzuk-neti** [comment]
Fix deployed today :+1:
