### ISSUE TITLE
Most recent round of allocation not showing in GH or allocator.tech

### ISSUE THREAD

**Issue by kevzak** [fidlabs/allocator-tooling#53]
A client was given 1300TiBs on May 17 but this allocation does not show:
-  in github issue  https://github.com/fidlabs/Enterprise-Data-Pathway/issues/18#issuecomment-2110200779
- or on allocator.tech https://allocator.tech/application/fidlabs/Enterprise-Data-Pathway/f1ty2ejqtsrifo6spbzlrneynfwarxsi53ctays4y

@willscott mentioned its likely related to last Keyko deploy that didn't work. Can the system be refreshed?

**Comment by kacperzuk-neti** [comment]
@kevzak Do I assume correctly that these 1300TiBs were handled manually, completely outside allocator.tech infrastructure?

**Comment by kevzak** [comment]
No @kacperzuk-neti it was completed inside allocator.tech. That's the issue. It was completed and never showed after in allocator.tech or github but it does exist onchain

**Comment by kacperzuk-neti** [comment]
@willscott do you have any details on this not working Keyko deploy?
I can see how it could be missing from allocator.tech, but it's quite surprising that there's also no trace of it on GitHub.

@kevzak Looks like it may be difficult to recover, but we'll try. Do you by any chance have the Cid of the message that granted the datacap?

**Comment by kevzak** [comment]
https://filfox.info/en/message/bafy2bzacebr72kbrr2qnduw75ons4mgbmf5fcyrozwemxtj4ybnucy6cdmzni?t=2

**Comment by kevzak** [comment]
I can't prove it, but I think any allocations made between May 13 and when your team took over are probably like this - not showing properly in allocator.tech/github

**Comment by kacperzuk-neti** [comment]
I can't find the root cause, but luckily it looks like it's not any allocations made between May 13 and the takeover. For example, here we have allocations on May 14th and 16th: https://allocator.tech/application/Blockchain-World-News/FIL-DC-Allocator/f1iilvoccl27nyy5ejsrxrz4b2huepu5xjlffnu7q .

We'll revisit finding the root cause if this happens again (as we'll have logs and other tools now to investigate). For now, I'll fix this manually (hopefully even today).

**Comment by kevzak** [comment]
@kacperzuk-neti anything here?

**Comment by kacperzuk-neti** [comment]
@kevzak state updated, please confirm that it's correct now.

**Comment by kevzak** [comment]
looks good
