### ISSUE TITLE
 Failure to trigger the next round of datacap allocations

### ISSUE THREAD

**Issue by MikeH1999** [fidlabs/allocator-tooling#54]
Exhaustion of quota in the first round does not trigger the next round of quota allocation
https://github.com/MikeH1999/RFfil/issues/31

![image](https://github.com/fidlabs/allocator-tooling/assets/149572051/9305ad12-689e-4be8-a601-75cb0378baf1)

**Comment by MikeH1999** [comment]
@willscott @kevzak

**Comment by kacperzuk-neti** [comment]
@MikeH1999 we're working on a workaround that would allow allocators to handle this manually when the automation fails - hopefully will be ready by the end of the week.

**Comment by galen-mcandrew** [comment]
Is this in regards to the **client** subsequent allocation? Meaning, after a client has received their first allocation of DC from an allocator, and then they start making deals, an automated request back to the allocator for the subsequent DC allocation?

I think that SA bot should still be getting developed.

_This is different from a bot requesting GovTeam review and more DataCap from the RKH. That is not yet in development, for triggering reviews when the entire allocator pathway has started running out of DataCap_

**Comment by kacperzuk-neti** [comment]
> Is this in regards to the client subsequent allocation? Meaning, after a client has received their first allocation of DC from an allocator, and then they start making deals, an automated request back to the allocator for the subsequent DC allocation?

Yes.

**Comment by yann-y** [comment]
@kacperzuk-neti can we manually handle it now？

**Comment by kacperzuk-neti** [comment]
Yea, we can. @MikeH1999 how big should the next allocation be?

**Comment by yann-y** [comment]
100TiB

**Comment by kacperzuk-neti** [comment]
Triggered, @MikeH1999 you can proceed with approving this: https://allocator.tech/application/MikeH1999/RFfil/f1ros77tqminx2v5ni3ley526333m3rdj7gg43hna

**Comment by MikeH1999** [comment]
Successful. Thank you.
