### ISSUE TITLE
Mistakenly granted extra DC

### ISSUE THREAD

**Issue by Fatman13** [fidlabs/allocator-tooling#55]
Hello, team,

I mistakenly granted extra [DC](https://github.com/filecoin-project/Allocator-Governance/issues/7) on allocator.tech. The UI prompted to me to input total DC to be allocated to this application and i put the amount but didn't expect it the amount for the first allocation (thought the UI would prompt me again for 1st allocation amount... the UI was very different than when i [first tested](https://github.com/py-guazi/GZ-FIP0078-Pathway/issues/3) out the process). The wording on the UI got me. Total as opposed to 1st allocation. Is there any way to fix this? Thank you.

**Comment by kevzak** [comment]
What amount are you talking about? 

I'm confused what did you do incorrectly @Fatman13 ? Five allocations of 1PiB were given. Where was mistaken extra DataCap granted?  

If you are saying something was a mistake, then you can request DataCap to be removed from the client. Reach out to gov team.

**Comment by kevzak** [comment]
I do see one application where 10PiBs was approved but that was not actually granted https://github.com/TVLimited/top-value-storage/issues/5#issuecomment-2058173149

**Comment by Fatman13** [comment]
Sorry bad wording. Will elaborate with screenshots...
