### ISSUE TITLE
No json file，Files can not automatically push into allocator github bookkeeping repo

### ISSUE THREAD

**Issue by METAVERSEDATAMINING** [fidlabs/allocator-tooling#57]
My allocator information is not here "https://github.com/filecoin-project/Allocator-Registry/tree/main/Allocators"
Please help to confirme it and add.
This is my Allocators application :https://github.com/filecoin-project/notary-governance/issues/1031

**Comment by METAVERSEDATAMINING** [comment]
I've been waiting on this [issue](https://github.com/filecoin-project/notary-governance/issues/1031#issuecomment-2032445085) for nearly two months now. 
What's the holdup? If there's any extra info you need from me, please let me know

**Comment by METAVERSEDATAMINING** [comment]
Hi@kevzak 
Can you assist me?
just incorporating my information into a JSON database?

**Comment by willscott** [comment]
the above linked notary-governance issue is the right place. this repo is for the allocator.tech tooling, and this team can't help you with the governance team approval process for allocators

**Comment by METAVERSEDATAMINING** [comment]
The issue has been solved.
