### ISSUE TITLE
The bot failed to reply to the approved request.

### ISSUE THREAD

**Issue by NewHuoPool** [fidlabs/allocator-tooling#59]
After I submitted the allocation request proposal, the bot failed to post a reply that  request  approved. I tried many times and still failed.
The bot indicated that the proposal was sent successfully, but did not  post any comments in the application.
[/issues/1](https://github.com/NewHuoPool/NewHuoPoolPathway)

![20240609091351](https://github.com/fidlabs/allocator-tooling/assets/117884185/65be4763-d0de-449c-9264-247e01101900)

**Comment by kacperzuk-neti** [comment]
This is caused by temporary problems in DMOB API used by allocator-tooling. We're in contact with DMOB API maintainers, who are working on a fix. I'll let you know when this is resolved.

Note for other devs:
```
filplus-backend-1  | [2024-06-09T00:21:49Z ERROR fplus_lib::core] Failed to retrieve allowance: Err("Error accessing DMOB api")
filplus-backend-1  | [2024-06-09T00:21:49Z INFO  actix_web::middleware::logger] 172.18.0.3 "POST /verifier/application/propose?repo=NewHuoPoolPathway&owner=NewHuoPool&id=f1kzg6jctjv7ymsidesasfp6lldmxa5nje4z4mxqi&github_username=NewHuoPool HTTP/1.1" 400 39 "https://allocator.tech/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36" 1.631670
```

**Comment by kacperzuk-neti** [comment]
@NewHuoPool please try now, API issues should be solved.

**Comment by NewHuoPool** [comment]
Hi@kacperzuk-neti ,Thank you for taking care of this promptly.
I'm not sure if the issue has been resolved,Based on my allocation guidelines, I am responsible for assigning 900T this round，but now whenever I submit any allocation quota, I get a message saying that the quota has been exceeded.  [/issues/1](https://github.com/NewHuoPool/NewHuoPoolPathway)


![20240610](https://github.com/fidlabs/allocator-tooling/assets/117884185/f639c801-f42b-46ed-b6a6-be862c2f9a81)

![202406100](https://github.com/fidlabs/allocator-tooling/assets/117884185/d28b808b-f75b-47b0-a4f7-37a796f3f1d8)

**Comment by NewHuoPool** [comment]
@kacperzuk-neti The previous issue should have been resolved. However, due to a lack of response from the bot, I submitted the request multiple times, resulting in an overdelivery of allocations. Please remove the allocations from this：f1kzg6jctjv7ymsidesasfp6lldmxa5nje4z4mxqi

**Comment by kacperzuk-neti** [comment]
@NewHuoPool can you list exactly which allocations should be removed? You can find a list here:
https://datacapstats.io/clients/f03096938/allocations

**Comment by NewHuoPool** [comment]
@kacperzuk-neti Please delete the five allocations highlighted in the box.


![20240611png](https://github.com/fidlabs/allocator-tooling/assets/117884185/a344fdce-45a7-4e99-b6dc-34eceaded64e)

**Comment by kevzak** [comment]
Request to remove DataCap submitted: https://github.com/filecoin-project/Allocator-Registry/issues/81
