### ISSUE TITLE
do not find my allocator on main screen of allocator.tech

### ISSUE THREAD

**Issue by METAVERSEDATAMINING** [fidlabs/allocator-tooling#60]
I found that there's a client application in my repo, but When going to the main screen of allocator.tech and logging in with my Github account, I couldn't find my [allocator](https://github.com/filecoin-project/notary-governance/issues/1031) . I've checked the following:
--My json document is in here [ json files](https://github.com/filecoin-project/Allocator-Registry/tree/main/Allocators)
--The bookkeeping document has also been pushed to the [repo](https://github.com/filplus-bookkeeping/METAVERSEDATAMINING), and the bookkeeping address is consistent with the json document.
After confirming these, I'm unsure where the problem is.

![fjg817](https://github.com/fidlabs/allocator-tooling/assets/111408360/daa9532d-b0ba-4122-9d4e-63764706ab54)

**Comment by METAVERSEDATAMINING** [comment]
@willscott @kevzak I need your help

**Comment by kacperzuk-neti** [comment]
@METAVERSEDATAMINING please try now and let me know if the issue was resolved.

**Comment by METAVERSEDATAMINING** [comment]
@kacperzuk-neti The previous issue has been resolved, but a new one has emerged. 
After submitting the DataCap Amount, there is no feedback, no pop-up notification, and the bot does not provide any feedback in the application comments.


![172324](https://github.com/fidlabs/allocator-tooling/assets/111408360/931ed78c-e69c-490c-967b-88dd9b2299ec)

**Comment by kacperzuk-neti** [comment]
@METAVERSEDATAMINING looks like there are some temporary issues with DMOB API that this relies on. I'll contact the DMOB API team and get back to you.

**Comment by kacperzuk-neti** [comment]
@METAVERSEDATAMINING please try now.

**Comment by METAVERSEDATAMINING** [comment]
@kacperzuk-neti Thank you for your assistance! The first batch has been signed. The labels provided by the bot are incorrect, and there was no prompt for 'granted'

![010](https://github.com/fidlabs/allocator-tooling/assets/111408360/e74bd304-0928-484e-adbb-33eac621e7fc)


![129](https://github.com/fidlabs/allocator-tooling/assets/111408360/bec00de0-e4ae-4849-8a41-92a03d708a65)

**Comment by kacperzuk-neti** [comment]
The system is correct. Your multisig has a threshold of 2. You've provided the first signature (which changed the state from `ready to sign` to `start sign datacap`) and the system is now waiting for the second signature (which will change state to `granted` and actually provide the allocation).
![image](https://github.com/fidlabs/allocator-tooling/assets/117277751/ae20645f-61b3-4a7c-81ef-3f502b9a39bb)

**Comment by METAVERSEDATAMINING** [comment]
@kacperzuk-neti Thank you very much, everything has been resolved.
