### ISSUE TITLE
NO CID Checker Report

### ISSUE THREAD

**Issue by METAVERSEDATAMINING** [fidlabs/allocator-tooling#62]
In the past week, after triggering reports, there has been no feedback data.
[comment-2167254815](https://github.com/filplus-bookkeeping/METAVERSEDATAMINING/issues/1#issuecomment-2167254815)
[comment-2177443850
](https://github.com/filplus-bookkeeping/METAVERSEDATAMINING/issues/1#issuecomment-2177443850)

**Comment by kacperzuk-neti** [comment]
Please try again now, it should be fixed.
I've also generated the report manually: https://check.allocator.tech/report/filplus-bookkeeping/METAVERSEDATAMINING/issues/1/1718886810267.md

**Comment by kacperzuk-neti** [comment]
Closing, please open a new issue if you're still affected by this.
