### ISSUE TITLE
NO bot CID Checker report

### ISSUE THREAD

**Issue by nicelove666** [fidlabs/allocator-tooling#63]
NO bot CID Checker report
https://github.com/nicelove666/Allocator-Pathway-IPFSTT/issues/27

**Comment by kacperzuk-neti** [comment]
Please try again now, it should be fixed.
I've also triggered the report manually: https://check.allocator.tech/report/nicelove666/Allocator-Pathway-IPFSTT/issues/27/1718886962090.md

**Comment by kacperzuk-neti** [comment]
Closing, please open a new issue if you're still affected by this.
