### ISSUE TITLE
Speeding up generation of compliance reports

### ISSUE THREAD

**Issue by martapiekarska** [fidlabs/allocator-tooling#64]
If I run a compliance report from compliance.allocator.tech it takes a few minutes to do it. Can we run the reports periodically (say every 24h?) and store them with a datastamp so that it is not generatef pre client request but more cached and updated if needed?

And when a new one is generated by a client - can it be stored for faster retrieval?

**Comment by kacperzuk-neti** [comment]
Done. Generation is cached, listed and now also should be much faster.
