### ISSUE TITLE
No “checker:manualTrigger” report

### ISSUE THREAD

**Issue by winter0707winter** [fidlabs/allocator-tooling#65]
<img width="1168" alt="image" src="https://github.com/user-attachments/assets/3bc36ca8-7c08-4212-8e1a-e0e57d276f9a">

https://github.com/Storify-LLC/Storify-Data-Pathway/issues/5#user-content-fnref-1-65a32b1d8ac0aff3d0bebc4deb051ed4

**Comment by kacperzuk-neti** [comment]
It doesn't show when looking at the issue, but there's a space character before the address in "On-chain address for first allocation" section in issue description. Edit the issue description, remove the space before the address and retrigger the checker.
