### ISSUE TITLE
address is not effective

### ISSUE THREAD

**Issue by FilscanOfficial** [fidlabs/allocator-tooling#67]
https://github.com/filecoin-project/notary-governance/issues/1033,
I kept getting an error during the approval process. I changed the address before. Is it because this address is not effective? Please help me check, thank you. Address: f16mbzjnlccbifopyt4fnd6u4iyd6mmojxtxcki7q
![image_720](https://github.com/user-attachments/assets/3b93d4ed-1db0-4d85-bd84-1b40a295c930)

![image](https://github.com/user-attachments/assets/7529a69c-5be6-4770-a2d5-952d775e323d)

**Comment by kacperzuk-neti** [comment]
This error suggests that something wrong went during the signing, regardless of the address used. Did you choose correct address from the list when connecting the Ledger on Allocator.tech? Can you describe step-by-step what happened during the approval process? Did something show on your Ledger device at all? Did you approve the transaction on the Ledger device?

Please share a screenshot of the browser console after the error appears ( https://balsamiq.com/support/faqs/browserconsole/#google-chrome )

**Comment by FilscanOfficial** [comment]
@kacperzuk-neti  Hello, thank you very much. I checked the problem today and it has been solved. Thank you for your hard work.

**Comment by kacperzuk-neti** [comment]
Happy to hear that!
