### ISSUE TITLE
No CID Report  Check

### ISSUE THREAD

**Issue by Chuangshi1** [fidlabs/allocator-tooling#69]
https://github.com/Chuangshi1/Genesis/issues/38
Here  is  the application link. 
There are no CID report check here. 
Hope you can help it.

**Comment by Chuangshi1** [comment]
@willscott @kevzak

**Comment by MikeH1999** [comment]
This should be an issue with the bot's data not updating in a timely manner, I've had it happen and waited 1-2 days for the data to be available

**Comment by kacperzuk-neti** [comment]
@Chuangshi1 CID Checker doesn't support DDO yet. Is this client doing DDO only?

**Comment by Bohden** [comment]
> @Chuangshi1 CID Checker doesn't support DDO yet. Is this client doing DDO only?

@kacperzuk-neti  yes

**Comment by Bohden** [comment]
When is DDO support expected?

@kacperzuk-neti

**Comment by kacperzuk-neti** [comment]
@Chuangshi1 @Bohden 
Please try now, CID Checker should now include DDO in the report.

**Comment by Chuangshi1** [comment]
> @Chuangshi1 @Bohden Please try now, CID Checker should now include DDO in the report.

It is Ok now. Thanks.
