### ISSUE TITLE
Repository is missing when I have more than one allocator using the same GitHub account

### ISSUE THREAD

**Issue by maxvint** [fidlabs/allocator-tooling#70]
I have 2 allocators, one is [CoinSummer Labs](https://github.com/filecoin-project/Allocator-Registry/blob/main/Allocators/1060.json), and another is [MinerDAO](https://github.com/filecoin-project/Allocator-Registry/blob/main/Allocators/1065.json).

<img width="1683" alt="image" src="https://github.com/user-attachments/assets/c26e2262-d965-4e91-b259-7dfaa91b3ff2">

I can only see Max-CoinSummer Labs in the drop-down menu under All Repositories, but Max-MinerDAO is missing.
What happened?

**Comment by kacperzuk-neti** [comment]
[MinerDAO](https://github.com/filecoin-project/Allocator-Registry/blob/main/Allocators/1065.json) has `Carohere` listed as an authorized github user (see `github_handles` field).
Please open a ticket in https://github.com/filecoin-project/Allocator-Registry/issues if you need it changed.
