### ISSUE TITLE
Complete verifier review got "Application is not in the correct state New: Failed to retrieve allowance"

### ISSUE THREAD

**Issue by maxvint** [fidlabs/allocator-tooling#71]
When I click "Complete verifier review" button on [allocator.tech](https://allocator.tech/), I got "Application is not in the correct state New: Failed to retrieve allowance", and I found the Allocator's DataCap balance is "NaNB".

<img width="2206" alt="image" src="https://github.com/user-attachments/assets/4203f14e-27ae-41d1-907d-49328845cda8">

I have requested pathway address modification in this issue https://github.com/filecoin-project/Allocator-Registry/issues/96.
I can sign before [this PR](https://github.com/filecoin-project/Allocator-Registry/pull/92) merged, but I can't sign now. It might be a bug related to the address modification.
Does the datacap need to be refreshed after the pathway address is modified?

**Comment by kacperzuk-neti** [comment]
>  Does the datacap need to be refreshed after the pathway address is modified?

Yes. datacap allowance is given to an address, so it needs to be refreshed after a change. The new address ( f23q74wvk6zq2dfopfe4wbt2tal2fkwicexcqui5q ) has no datacap allowance, so can't allocate it to clients. Also, the old address still has 5PiB which should probably be removed if it's not going to be used. Please work with the governance team on sorting this out.

**Comment by kacperzuk-neti** [comment]
Closing, as this needs to be handled on the governance side now. Please open a new issue if needed for anything.
