### ISSUE TITLE
https://github.com/FilscanOfficial/filscan-backend/issues/9  Allocation Problem

### ISSUE THREAD

**Issue by FilscanOfficial** [fidlabs/allocator-tooling#74]
hello，I encountered a problem: https://github.com/FilscanOfficial/filscan-backend/issues/9 This link applies for 3P. I have approved 2P. When approving the next 500T, the first error message was: An error with the lotus node occurred. Please reload. If the problem persists, contact support. After the second approval, it became 0T. Now I can't operate it anymore. What should I do?
![image](https://github.com/user-attachments/assets/17c496c3-6fc1-4e19-ac88-164273602209)

**Comment by FilscanOfficial** [comment]
Can this be resolved today? Since the client is in a hurry to use it, if it cannot be resolved today, I plan to ask the client to submit a new application tomorrow for approval.

**Comment by kacperzuk-neti** [comment]
@FilscanOfficial no, this won't be solved today.

**Comment by FilscanOfficial** [comment]
I closed this link

**Comment by kacperzuk-neti** [comment]
@FilscanOfficial while we weren't able to identify a root cause yet, the application should be unblocked now (you should be able to trigger a new refill).

**Comment by FilscanOfficial** [comment]
@kacperzuk-neti Since the client is in a hurry, I am not sure how long it will take to resolve the issue. I have suggested that the client close the original link and reapply. This issue can be closed now. Thank you very much.
