### ISSUE TITLE
Github account is not recognized as verifier

### ISSUE THREAD

**Issue by Filedrive-ops** [fidlabs/allocator-tooling#75]
The account Filedrive-ops is added to allocator as described in   https://github.com/filecoin-project/Allocator-Registry/issues/169 

And here is new json: https://github.com/filecoin-project/Allocator-Registry/blob/main/Allocators/1030.json

But the DC assignment tool https://allocator.tech is unable to recognize the account Filedrive-ops as the verifier. Could you please assist? Thank you.

<img width="1101" alt="image" src="https://github.com/user-attachments/assets/cca1a801-a3c1-49a2-a14d-240c15437bf1">

**Comment by kacperzuk-neti** [comment]
The JSON is invalid, so the update wasn't applied. I've opened a PR with a fix, but it needs to be merged by someone from the governance team.

**Comment by kacperzuk-neti** [comment]
Looks like JSON was fixed and I see it is now correctly updated in Allocator.tech.
