### ISSUE TITLE
New allocator signer doesn't work

### ISSUE THREAD

**Issue by Filedrive-ops** [fidlabs/allocator-tooling#76]
The new signer, f1vewqfhde62bjccdiy3qbjbhg37ldr4y7nm5wv6q, has been added to the allocator as described in filecoin-project/Allocator-Registry#169.

Here is the updated JSON: [1030.json](https://github.com/filecoin-project/Allocator-Registry/blob/main/Allocators/1030.json).

However, the new address does not appear in the address list when the Data Center Assignment Tool at [allocator.tech](https://allocator.tech/) connects with the Ledger. Please find the attached screenshot showing the address list, with the first one being the previous signer. Could you please assist with this issue? Thank you.
<img width="296" alt="image" src="https://github.com/user-attachments/assets/72c43588-6198-471c-a8d0-f929c63ca1f1">

**Comment by kacperzuk-neti** [comment]
@Filedrive-ops this list shows accounts that are available on the connected ledger, it doesn't reference the JSON file. Where did `f1vewqfhde62bjccdiy3qbjbhg37ldr4y7nm5wv6q` address come from originally? If you're certain that this Ledger contains this address, try clicking `Load more`.

**Comment by Filedrive-ops** [comment]
@kacperzuk-neti 

Thank you for your support. I found the address, and it works.
