### ISSUE TITLE
Can't generate compliance report

### ISSUE THREAD

**Issue by Filedrive-ops** [fidlabs/allocator-tooling#78]
I run checker:manualTrigger but no report was generated either on 
https://github.com/filedrive-team/Filecoin-Plus-Pathway/issues/3 or https://github.com/filedrive-team/Filecoin-Plus-Pathway/issues/5
As checked with clients, both of those DC have been assigned and sealed. Could you let me how to generate the report? thank you. 
<img width="1079" alt="image" src="https://github.com/user-attachments/assets/8e62ac95-7a5b-4805-ba78-98d9a276f755">
<img width="1079" alt="image" src="https://github.com/user-attachments/assets/c13ba170-1da9-46fe-9fc2-4815c93e3a6b">

**Comment by kacperzuk-neti** [comment]
@Filedrive-ops Thanks for reporting. Our data provider is missing data for these clients. I've contacted the team responsible and will update you when I have any additional details.

**Comment by kacperzuk-neti** [comment]
@Filedrive-ops 
Data is synced once a day at 8am GMT. DC for these clients was sealed yesterday, so it wasn't yet available for compliance tools when you tried it. I see that it was synced - give it a go again and it should generate reports properly.

**Comment by Filedrive-ops** [comment]
@kacperzuk-neti 
It works perfectly. Thank you so much for your prompt support!

**Comment by MikeH1999** [comment]
Synchronizing data once a day is too slow, can you speed it up?I understand that it will be changed to hourly or bi-hourly synchronization.

**Comment by kacperzuk-neti** [comment]
> Synchronizing data once a day is too slow, can you speed it up?I understand that it will be changed to hourly or bi-hourly synchronization.

I'll raise this issue with the data provider.

**Comment by Filip-L** [comment]
@MikeH1999 The synchronization frequency has been changed, from now on it should be done every 2 hours.

**Comment by MikeH1999** [comment]
That's great.

**Comment by jauea** [comment]
>The synchronization frequency has been changed, from now on it should be done every 2 hours.

@Filip-L It doesn't seem to be working.

**Comment by kacperzuk-neti** [comment]
@jauea right now the data provider is having issues and nothing is being synced at all. They're working on a fix. Sorry!

**Comment by kacperzuk-neti** [comment]
Data provider fixed the syncing, it should work correctly (update every 2 hours) now.
