### ISSUE TITLE
Robot not triggered

### ISSUE THREAD

**Issue by Lind111** [fidlabs/allocator-tooling#8]
https://github.com/Lind111/EF/issues/2

**Comment by Lind111** [comment]
![image](https://github.com/fidlabs/allocator-tooling/assets/130743579/ca9caa22-374a-465c-9a55-be30af2e2945)

**Comment by willscott** [comment]
Interesting - it looks like the action is still pending from github:

see https://github.com/Lind111/EF/actions/runs/8355416058

<img width="1162" alt="image" src="https://github.com/fidlabs/allocator-tooling/assets/428199/ce3d328a-23d7-4534-b5e6-099d16af1425">

**Comment by Lind111** [comment]
So what do I do?

**Comment by willscott** [comment]
It looks like the worker eventually triggered. was there anything you had to do?

**Comment by Lind111** [comment]
I see it, but it's been too long.
