### ISSUE TITLE
Can not create branch

### ISSUE THREAD

**Issue by Lind111** [fidlabs/allocator-tooling#80]
![image](https://github.com/user-attachments/assets/b0aab4fc-83e4-4977-aec6-318f287054ad)
@kacperzuk-neti @Filip-L Have a new question not sure if this is causing it?Can you help look at it?
https://github.com/Lind111/EF/issues/27

**Comment by kacperzuk-neti** [comment]
Looking into it.

**Comment by kacperzuk-neti** [comment]
@Lind111 please try again now.
