### ISSUE TITLE
Datacap granted twice & not recorded in allocator.tech

### ISSUE THREAD

**Issue by kacperzuk-neti** [fidlabs/allocator-tooling#82]
https://github.com/AlanGreaterheat/Greaterheat-Allocator/issues/9

Allocator sent 2 messages to grant to `f1glikceorqrsklnndkcnkoqb7lireurgv2liwobq`:
* 2024-10-28 09:11:00 - https://filfox.info/en/message/bafy2bzaceblugeqys3h32cs7lgpa6fxniygzjkq7pit3aesdh2eubrvrgxck2?t=2
* 2024-10-28 09:12:30 - https://filfox.info/en/message/bafy2bzacebxewcptozg4v4gl4zy5lxsejfaqoxpd57x3v3tjkfciceik4y6pq?t=2

None of them got recorded by Allocator.tech (fix for the root cause is being worked on).

We need to update the application json file in Allocator's repo to record missing allocations manually.

cc @AlanGreaterheat

**Comment by kacperzuk-neti** [comment]
@AlanGreaterheat
Do you remember if something out of ordinary happened after you approved transactions on Ledger?

**Comment by AlanGreaterheat** [comment]
Yes, Greaterheat Allocator actually had 2PiB Datacap remaining before I made the approval, but after I linked the ledger wallet, this glitch appeared, see the screenshot for details.

<img width="1273" alt="image" src="https://github.com/user-attachments/assets/141e3088-0f00-42dd-a6b1-1d130d95549c">

When the above failure occurred, I tried the button “Revert Pending Allocation”.

I tried the same on both apps:
https://github.com/AlanGreaterheat/Greaterheat-Allocator/issues/9
https://github.com/AlanGreaterheat/Greaterheat-Allocator/issues/11

<img width="1426" alt="image" src="https://github.com/user-attachments/assets/6e4c27ca-523a-4a64-9153-ff7460b972ce">

**Comment by AlanGreaterheat** [comment]
https://github.com/AlanGreaterheat/Greaterheat-Allocator/issues/11

This client ran into the same problem at about the same time.

I don't know if it's because two different applications are applying for allocator approval at the same time.

**Comment by kacperzuk-neti** [comment]
@AlanGreaterheat so this part is not a glitch.

Client `f1glikceorqrsklnndkcnkoqb7lireurgv2liwobq` got the datacap twice, `1PiB` each. So if Greaterheat Allocator had `2PiB` before, it's correct that it now has no datacap.

The glitch was that `f1glikceorqrsklnndkcnkoqb7lireurgv2liwobq` got the datacap and it didn't show up on allocator.tech and allowed you to try again (which also wasn't recorded as it should). Do you remember what happened after you first approved datacap grant on the Ledger for `f1glikceorqrsklnndkcnkoqb7lireurgv2liwobq`? Did it show you a success message that the message was sent?

**Comment by AlanGreaterheat** [comment]
<img width="1234" alt="image" src="https://github.com/user-attachments/assets/2529e5e7-cfc9-4875-bcc4-ee1ede74b11c">

But this recharge display seems to look different than before

The following screenshot shows the previous top-up display without any problems.


<img width="1037" alt="image" src="https://github.com/user-attachments/assets/005fd1d4-4e9d-4246-a408-f679cbb80b71">

**Comment by AlanGreaterheat** [comment]
> @AlanGreaterheat so this part is not a glitch.
> 
> Client `f1glikceorqrsklnndkcnkoqb7lireurgv2liwobq` got the datacap twice, `1PiB` each. So if Greaterheat Allocator had `2PiB` before, it's correct that it now has no datacap.
-------- This is what we understand to be consistent.
> 
> The glitch was that `f1glikceorqrsklnndkcnkoqb7lireurgv2liwobq` got the datacap and it didn't show up on allocator.tech and allowed you to try again (which also wasn't recorded as it should).
-------- Yes, that's right.

 Do you remember what happened after you first approved datacap grant on the Ledger for `f1glikceorqrsklnndkcnkoqb7lireurgv2liwobq`? 
 ------- - I don't have a screenshot, but a line of text just appeared that didn't make it clear that the recharge was successful anyway. That's why another attempt was made.
 
 Did it show you a success message that the message was sent?
——————————No, it didn't, so in the end I saw that address recharged 2 PiB indicating that it was strange, and I can also see on the application request that the recharge success is displayed differently than before.

**Comment by AlanGreaterheat** [comment]
Information is updated: @kacperzuk-neti 

We have been told by a partner that they also had some problems with the signing site, as the following icon shows almost 3-4 minutes of time, although in the end the signing went through without any problems.

It looks like there is a delay in the signature response time.

<img width="1226" alt="image" src="https://github.com/user-attachments/assets/d6a977f9-ec73-4ca1-8bd1-21fd68666052">

**Comment by kacperzuk-neti** [comment]
> We have been told by a partner that they also had some problems with the signing site, as the following icon shows almost 3-4 minutes of time, although in the end the signing went through without any problems.

This is perfectly normal. This stays open until the transaction is confirmed on chain, and depending on the network congestion it can take a few minutes.

**Comment by kacperzuk-neti** [comment]
@AlanGreaterheat I have manually restored the 2 allocations that weren't recorded on-chain. While it's not completely clear why this happened, we're in a process of reworking this part of the system in a way that will make it impossible to happen, though that will be released in 1-2 weeks from now.
Until now, please make sure that after you approve message on Ledger, you wait for the loading on the page to finish before closing it. That will make sure it does get recorded as it should.

**Comment by AlanGreaterheat** [comment]
https://github.com/AlanGreaterheat/Greaterheat-Allocator/issues/9

I would like to confirm that the 2PiB Datacap for this client is available?

 Also, you're right, the necessary wait of a few minutes is mandatory until the chain confirmation is complete
> From: "Kacper Żuk ***@***.***>
> Date:  2024年10月29日 (周二) 21:25
> Subject:  Re: [fidlabs/allocator-tooling] Datacap granted twice & not recorded in allocator.tech (Issue #82)
> To: ***@***.***>
> Cc: ***@***.***>, ***@***.***>
> @AlanGreaterheat<https://github.com/AlanGreaterheat> I have manually restored the 2 allocations that weren't recorded on-chain. While it's not completely clear why this happened, we're in a process of reworking this part of the system in a way that will make it impossible to happen, though that will be released in 1-2 weeks from now.
> 
Until now, please make sure that after you approve message on Ledger, you wait for the loading on the page to finish before closing it. That will make sure it does get recorded as it should.

**Comment by kacperzuk-neti** [comment]
> I would like to confirm that the 2PiB Datacap for this client is available?

Yes, this client received 2 PiB yesterday, as can be confirmed here: https://datacapstats.io/clients/f03063386/allocations . Currently this client has 2.03 PiB of Datacap available.

![image](https://github.com/user-attachments/assets/e327cfde-5c6c-4d0c-8916-37f5c2ef2fbc)

**Comment by AlanGreaterheat** [comment]
Haha,2PiB😀,not 2TiB

**Comment by AlanGreaterheat** [comment]
Thank you very much!🫡
Thanks for the efficient feedback!

**Comment by kacperzuk-neti** [comment]
> Haha,2PiB😀,not 2TiB

Yes, of course, sorry :sweat_smile: .
