### ISSUE TITLE
（BUG）—— Robot report delayed trigger, unable to view sealing report

### ISSUE THREAD

**Issue by pandacrypto** [fidlabs/allocator-tooling#83]
https://github.com/pandacrypto/DSPA-Allocator/issues/11

https://github.com/pandacrypto/DSPA-Allocator/issues/6

https://github.com/pandacrypto/DSPA-Allocator/issues/14

<img width="1095" alt="image" src="https://github.com/user-attachments/assets/43b026e7-d1a5-4b30-96f2-6fda16b453f1">

<img width="1066" alt="image" src="https://github.com/user-attachments/assets/5ffe86ec-1a3b-4ae3-bd8c-884763c93a5d">

<img width="1143" alt="image" src="https://github.com/user-attachments/assets/0a4ef10b-f4e3-4220-8103-176713aa12e6">

**Comment by kacperzuk-neti** [comment]
@pandacrypto thanks for the report, we've identified the root cause and implemented a workaround. As you can see in your applications, reports were generated now.
