### ISSUE TITLE
New applications not visible on the allocator.tech

### ISSUE THREAD

**Issue by CloudX-Lab** [fidlabs/allocator-tooling#84]
Client has applied to my [repo](https://github.com/CloudX-Lab/filecoin/issues). https://github.com/CloudX-Lab/filecoin/issues/17

But I can't review his application on https://allocator.tech/. 
https://github.com/CloudX-Lab/filecoin/issues/18 
https://github.com/CloudX-Lab/filecoin/issues/19
I've let client reapply new applications twice, but nothing works.
![image](https://github.com/user-attachments/assets/01792692-9428-4849-b1b0-fe3ec27edb09)

Please help solve this bug.

**Comment by kacperzuk-neti** [comment]
Your repo is `CloudX-Lab/filecoin`. But the governance-approved repo in [allocator registry](https://github.com/filecoin-project/Allocator-Registry/blob/b5ada2c1e2e675d4ca79735614e702800e5f1e83/Allocators/1001.json#L32) is `CloudX-Lab/filecion` (notice the typo). These need to match, as repos that don't match the registry are ignored.

Do I assume correctly, that the repo was renamed to fix the typo? If yes, then please open an issue on https://github.com/filecoin-project/Allocator-Registry/issues asking to get this updated in the registry as well.

**Comment by CloudX-Lab** [comment]
@kacperzuk-neti Thank you!
