### ISSUE TITLE
Can't allocate DC to client

### ISSUE THREAD

**Issue by ipfsforcezuofu** [fidlabs/allocator-tooling#85]
Hello,

I'm allocating DC to client https://github.com/ipfsforcezuofu/ipfsforce-allocator/issues/21 . After entering the amount of 500T and submitting, I connected the ledger and selected the first address.

<img width="280" alt="image" src="https://github.com/user-attachments/assets/fb22ae2b-fa55-4fa8-b161-b66f30bedb23">

Upon clicking the "Propose" button, the following error message appeared.
<img width="764" alt="image" src="https://github.com/user-attachments/assets/b717e807-9db5-4b90-8372-77804a56641c">

**Comment by kacperzuk-neti** [comment]
@ipfsforcezuofu Thanks for the report. Did you get a chance to confirm the transaction on Ledger device or did it immediately show up after clicking "Propose", without interacting with Ledger?

**Comment by ipfsforcezuofu** [comment]
@kacperzuk-neti 
It  shows immediately without any action on Ledger.

**Comment by kacperzuk-neti** [comment]
Please share a screenshot of the browser console right after the error appears.

Instruction on how to open browser console: https://balsamiq.com/support/faqs/browserconsole/

**Comment by ipfsforcezuofu** [comment]
<img width="995" alt="image" src="https://github.com/user-attachments/assets/b9a58868-22ed-461b-8d53-635301a99f0a">

**Comment by ipfsforcezuofu** [comment]
@kacperzuk-neti 

I believe the issue was caused by manually entering the amount as 500**T.** Today, I tried using 500**TiB** instead, and it worked, although the screen still shows as busy. The assignment has been confirmed through [Glif Verify](https://verify.glif.io/).
<img width="88" alt="image" src="https://github.com/user-attachments/assets/0d9e97ee-53b0-452e-8021-b920d75da804">

**Comment by kacperzuk-neti** [comment]
> I believe the issue was caused by manually entering the amount as 500T. Today, I tried using 500TiB instead, and it worked, although the screen still shows as busy.

Thanks for figuring it out, indeed we don't handle invalid units (like `T`) properly! I've added it to our backlog to fix.

> although the screen still shows as busy

This is expected. The screen waits for the transaction to get confirmed on Filecoin network, which can take even a few minutes. We're working on a change that will make this clearer and not require you to wait for it to finish :+1:
