### ISSUE TITLE
Can't propose dc to client

### ISSUE THREAD

**Issue by OpenGate01** [fidlabs/allocator-tooling#86]
The 500T datacap has been triggered, however, we are encountering bugs when proposing the dc to the client address.
![WechatIMG3797](https://github.com/user-attachments/assets/26fed6d6-c0fe-4d1c-882c-04571a2fdc63)

**Comment by kacperzuk-neti** [comment]
@OpenGate01 you're trying to grant 500TiB datacap to a client, but your allocator only has 36TiB of datacap left. Either grant less or ask the governance team for a refill.

**Comment by kacperzuk-neti** [comment]
Closing issue as this needs to be handled by the governance.
