### ISSUE TITLE
Changed signer doesn't work

### ISSUE THREAD

**Issue by VenusOfficial** [fidlabs/allocator-tooling#87]
Hello,

I've applied for the signer change in [this GitHub issue](https://github.com/filecoin-project/Allocator-Registry/issues/128). I tried to assign new DC to the client in [this issue](https://github.com/VenusOfficial/Pathway-VFDA/issues/54). After connecting the ledger and selecting the address,  I received the following error message. Could you help to check? Thank you so much.
<img width="741" alt="image" src="https://github.com/user-attachments/assets/7e25cb3c-8b0a-4c31-9a6d-f9695af591a4">

**Comment by kacperzuk-neti** [comment]
@VenusOfficial this error means that this new address doesn't yet exist on Filecoin network. You can confirm this by checking it on Filfox: https://filfox.info/en/address/f1wzmrjlhu244jyjlpsjlyhp7en35ue4wpwbfsv3y . It says `ID: --` which means that it doesn't exist (yet). Also, this address doesn't have any FIL to pay for transaction fees.
Best way to create it on the network is to just send some FIL to it. Then it should work properly.

**Comment by VenusOfficial** [comment]
@kacperzuk-neti  The previous error message disappeared after some FIL was transferred to the address. However, a new error message has appeared. Could you check again? Thanks.
<img width="756" alt="image" src="https://github.com/user-attachments/assets/53c45813-301a-43ef-aaee-1e99d8df383d">

**Comment by kacperzuk-neti** [comment]
@VenusOfficial this error means that `f1wzmrjlhu244jyjlpsjlyhp7en35ue4wpwbfsv3y` address is NOT an authorized signer of your Allocator's multisig. So looks like the signer address was only changed in the registry JSON, but not on-chain.
You can confirm this here: https://filfox.info/en/address/f2hxivxs3we5afsuyx32lwwn44evopz7yea2fsmhy . It lists current signers as:
* `f1a5b5cn5xgsmui2kivzj2eryzrqmhmew4tytj3by`
* `f1mkeafrmvg3tiuugtcwpyumjbuyeoey3t2exa4ba`

You need to contact the governance team and ask them to update signers in the multisig.

**Comment by OpenGate01** [comment]
Copy that,I will try tomorrow.Thanks.

**Comment by kacperzuk-neti** [comment]
Closing issue as this needs to be fixed on the multisig.
