### ISSUE TITLE
Signature success status unchanged

### ISSUE THREAD

**Issue by luhong123** [fidlabs/allocator-tooling#89]
![image](https://github.com/user-attachments/assets/95c7534d-7f2c-430c-8aad-1e67f69a683f)
The error popped up without taking a screenshot in time, the balance has been deducted, but the status is still Pending Signatures
https://github.com/luhong123/QC-Data-center/issues/3

**Comment by hash889900** [comment]
![image](https://github.com/user-attachments/assets/d915556f-a3b8-4a0e-9c79-e35ac84579e5)
I seem to be having this problem, is that right?

**Comment by hash889900** [comment]
https://github.com/hash889900/HashTeam/issues/8

**Comment by hash889900** [comment]
![image](https://github.com/user-attachments/assets/eee8bc1c-d745-4d73-9ef6-0bc59dccefc7)
A new error.
https://github.com/hash889900/HashTeam/issues/24

**Comment by kacperzuk-neti** [comment]
Thanks for the report! Looks like last update have gone wrong.
Please don't try again, that will result in a double-spend.
We'll fix this shortly.

**Comment by kacperzuk-neti** [comment]
@luhong123 
* Application https://allocator.tech/application/luhong123/QC-Data-center/f1rbeabu5yjok6gicq757344w3w6wlbuujpomccua - missing allocation was added and the state of the application was updated. 

@hash889900 
* Application https://allocator.tech/application/hash889900/HashTeam/f1mpypjmz4xxcxy3oql7ksxa2ggczoaetbvxq2qxq - missing allocation was added and the state of the application was updated. 
* Application https://allocator.tech/application/hash889900/HashTeam/f1ns5wc5rbn3dmhc3wq3chsxyx556tfrze5la3zqa - missing allocation was added and the state of the application was updated.

Update was reverted, so this shouldn't happen again. Feel free to resume normal operations.
