### ISSUE TITLE
In allocator tech add flexibility for granted datacap amount

### ISSUE THREAD

**Issue by willscott** [fidlabs/allocator-tooling#9]
* should have an option for allocator to set their percentages in their allocator-registry json, and then use those percentages of the total request
* should have the option for allocator to set fixed allocation amounts ( like '1tb') and use those amounts 
* should have an option for a manually entered amount.

**Comment by MikeH1999** [comment]
This should be on the agenda, for my first round I was going to allocate only 50Tb,but I couldn't enter it. Only the default

**Comment by MikeH1999** [comment]
I can assist with testing

**Comment by MikeH1999** [comment]
Has the feature been launched yet?
