### ISSUE TITLE
New signer doesn't work

### ISSUE THREAD

**Issue by VenusOfficial** [fidlabs/allocator-tooling#91]
Hello,

Kevin assisted in adding a new signer to the allocator as detailed in [this issue](https://github.com/filecoin-project/notary-governance/issues/1035) and modified the new JSON file accordingly [here](https://github.com/filecoin-project/Allocator-Registry/blob/main/Allocators/1035.json). However, upon connecting the ledger and proposing on [allocator.tech](https://allocator.tech/), I received the following error message:

"Message execution failed: exit ErrForbidden(18), reason: message failed with backtrace: 00: f03019831 (method 2) -- f03236388 is not a signer (18) (RetCode=18)."

Could you please assist? Thank you!

**Comment by kacperzuk-neti** [comment]
This means that the new address is not a signer in your multisig.
Adding to JSON is not enough (it's only there for documentation purposes) - it needs to be added onchain. Please reach out to the Governance Team again.

**Comment by VenusOfficial** [comment]
@kacperzuk-neti 
Thank you for your so detail explanation!
