### ISSUE TITLE
DataCap and CID Checker Report  data has not been updated.

### ISSUE THREAD

**Issue by NDLABS-Leo** [fidlabs/allocator-tooling#92]
https://github.com/NDLABS-Leo/Allocator-Pathway-Enterprise-data/issues/25

The data has not been updated.

**Comment by kacperzuk-neti** [comment]
We were notified by the data provider that data processing was stuck. It's been fixed and is now catching up. Data should be back tomorrow.

**Comment by kacperzuk-neti** [comment]
Data should be up-to-date now (lag of 3-4h max).
