### ISSUE TITLE
Load: Failed to get application file

### ISSUE THREAD

**Issue by zcfil** [fidlabs/allocator-tooling#93]
![image](https://github.com/user-attachments/assets/e60d7463-ed80-4d6d-a033-22e3a8c079e4)

https://github.com/zcfil/ZCFIL/issues/6

**Comment by zcfil** [comment]
The relevant information is also inconsistent
![image](https://github.com/user-attachments/assets/37e6f0b5-493d-4b35-bb65-84fad7fe3ece)
Backstage Display
![image](https://github.com/user-attachments/assets/bc73d4b1-5a56-49a2-8cb6-d22347949b59)

**Comment by kacperzuk-neti** [comment]
@zcfil when do you see this error? After clicking `Trigger Refill`? Does it still happen when you try it now?

> The relevant information is also inconsistent

It shows as 15 PiB right now. I assume that's because it was modified 5 days ago in the GH issue and only approved 5 hours ago - it only updates after the approval.

**Comment by zcfil** [comment]
>After clicking Trigger Refill

yes

**Comment by zcfil** [comment]
>Does it still happen when you try it now?

yes

**Comment by zcfil** [comment]
@kacperzuk-neti Can this problem be solved immediately?

**Comment by Filip-L** [comment]
Hey @zcfil, we probably solved your issue, your application is again in "Changes requested" state with up-to-date changes. You can approve the changes and trigger a refill. Please let me know if this works for you.

**Comment by kacperzuk-neti** [comment]
Closing, as I see that the application is now granted, so the issue was resolved.

**Comment by zcfil** [comment]
Thanks
