### ISSUE TITLE
Bug ：Robot reports no triggers

### ISSUE THREAD

**Issue by zoufang567653** [fidlabs/allocator-tooling#94]
https://github.com/Storify-LLC/Storify-Data-Pathway/issues/19

![image](https://github.com/user-attachments/assets/792e133d-a8b2-4c6a-99c0-e0c9f4d5af42)
When the application request is submitted, the robot does not show any steps

**Comment by Timothea01** [comment]
https://github.com/filplus-bookkeeping/TopBlocks/issues/25

likewise

**Comment by kacperzuk-neti** [comment]
Thanks for the report, looking into it.

**Comment by kacperzuk-neti** [comment]
@zoufang567653 @Timothea01 @winter0707winter
The issue was resolved, new applications should now be recognized and visible in allocator.tech.
