### ISSUE TITLE
Robot auto-recognition failure

### ISSUE THREAD

**Issue by winter0707winter** [fidlabs/allocator-tooling#95]
https://github.com/liyunzhi-666/TianjiStudio-Fil/issues/8

<img width="1098" alt="image" src="https://github.com/user-attachments/assets/f3d5f91f-419d-494f-817c-38510aab1ddc">

<img width="1352" alt="image" src="https://github.com/user-attachments/assets/562d6ebd-39e2-4e81-8188-2a2d85e92f4f">

**Comment by kacperzuk-neti** [comment]
Closing as a duplicate of #94 - please follow #94 for updates.
