### ISSUE TITLE
Robot sealing report unrecognized, unable to view sealing situation

### ISSUE THREAD

**Issue by Laycuicui** [fidlabs/allocator-tooling#96]
https://github.com/Blockchain-World-News/FIL-DC-Allocator/issues/38

**Comment by kacperzuk-neti** [comment]
@Laycuicui thanks for the report. The issue was fixed and the report was generated: https://github.com/Blockchain-World-News/FIL-DC-Allocator/issues/38#issuecomment-2500316322
