### ISSUE TITLE
SP saves CAR, The retrieval very low

### ISSUE THREAD

**Issue by usejsi** [fidlabs/allocator-tooling#97]
https://github.com/nicelove666/Allocator-Pathway-IPFSTT/issues/96
https://check.allocator.tech/report/nicelove666/Allocator-Pathway-IPFSTT/issues/96/1733129829060.md

After many communications with SPs, we confirmed that all SPs have saved all CAR files. so, their support rate for Spark should be 100%.
But it seems to be very low.
Especially after the network upgrade, the retrieval rate of f02883857 is very unstable. Now that a few weeks have passed, the retrieval rate of f02883857 is still very low.

<img width="1039" alt="WX20241202-165740@2x" src="https://github.com/user-attachments/assets/38fd3042-e3f1-4f36-a0ce-fb8333aa380e">

We have tried many ways and found many reasons, but it seems that the problem has not solved.

This is our random retrieval for f02883857.
<img width="721" alt="WechatIMG803" src="https://github.com/user-attachments/assets/b41a0bad-e35f-4fa3-b0f4-ccfcf42e184f">

<img width="713" alt="WechatIMG804" src="https://github.com/user-attachments/assets/b02af0ba-ae3a-47dd-be82-9ae155464f3c">
<img width="723" alt="WechatIMG802" src="https://github.com/user-attachments/assets/f0a2d860-171d-41e0-af7d-bf45782468cf">

**Comment by kacperzuk-neti** [comment]
Hi @usejsi . Retrieval is measured by Spark, not by FIDL, so we can't really help you.
Please try following this guide: https://docs.filspark.com/troubleshooting-miner-score . If it doesn't help, reach out to Spark team on [Filecoin Slack](http://filecoin.io/slack) in the channel [#station](https://filecoinproject.slack.com/archives/C03S6LXSRB8) or write via email [spark@meridian.space](mailto:spark@meridian.space).
