### ISSUE TITLE
Two days after the sealing, no data has been reported.

### ISSUE THREAD

**Issue by MikeH1999** [fidlabs/allocator-tooling#99]
issue：https://github.com/MikeH1999/RFfil/issues/54

![image](https://github.com/user-attachments/assets/5afd672f-7352-4375-bb52-593a17c13e45)

**Comment by kacperzuk-neti** [comment]
The problem was that there was a space character (` `) at the start of the client's address in the application text.
We've updated the bot to handle that gracefully and the report was generated.
Sorry for trouble!
